# Generated by Django 5.0.1 on 2024-02-02 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('contactno', models.CharField(max_length=50)),
                ('Whatsappno', models.CharField(max_length=50)),
                ('available', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
