# Generated by Django 5.0.1 on 2024-02-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profilePhoto',
            field=models.ImageField(blank=True, upload_to='Lsp/'),
        ),
    ]
