# Generated by Django 5.0.1 on 2024-02-02 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp', '0002_serviceprovider_profilephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=100)),
                ('customerPhone', models.CharField(max_length=30)),
                ('customerAddress', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('accepted', models.BooleanField()),
                ('customerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requestbox', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_requestbox', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
