# Generated by Django 5.0.1 on 2024-02-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lsp', '0009_alter_booklogs_user_alter_requestbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
